spring.application.name=blep

# 127.0.0.1 port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/blep_dp
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
