spring.application.name=blep

#spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
#spring.datasource.username=your_username
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=org.postgresql.Driver

# 127.0.0.1 port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/blep_dp
spring.datasource.username=postgres
spring.datasource.password=101112
spring.datasource.driver-class-name=org.postgresql.Driver
